-- Generated by nwg-displays on 2026-08-25 at 13:27:42. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "3230x2700",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@143.98",
    position = "4310x3170",
    scale = 1
})
